name: Build Python artifacts

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      source-path:
        required: true
        type: string
      setup-file:
        required: true
        type: string
      watched-paths:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      artifact-name:
        required: true
        type: string
      source-path:
        required: true
        type: string
      setup-file:
        required: true
        type: string

jobs:
  check-changed-files:
    name: Check for changed files
    runs-on: ubuntu-latest
    container: node:18
    outputs:
      any-changed: ${{ github.event_name == 'workflow_dispatch' || steps.changed-files.outputs.any_changed == 'true'}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files list
        uses: tj-actions/changed-files@v34
        id: changed-files
        with:
          files: ${{ inputs.watched-paths }}

  build-artifacts:
    name: Package ${{ inputs.artifact-name }}
    runs-on: ubuntu-latest
    container: node:18
    needs: check-changed-files
    if: needs.check-changed-files.outputs.any-changed == 'true'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Prepare repo for packaging
        run: |
          if [[ -f '${{ inputs.source-path }}/README.md' ]]; then
            mv ${{ inputs.source-path }}/README.md README.md
          fi
          mv ${{ inputs.setup-file }} setup.py
      - name: Build wheel and source
        run: |
          python3 -m pip install build
          python3 -m build --sdist --wheel --outdir dist
      - name: Upload dists
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: ./dist
