name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./test.sh
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
