name: Matrix Grouping
on: [push]

jobs:
  job-b:
    name: Job B ${{ matrix.bar }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4, 5]
        include:
          - foo: 1
            bar: 'bar'
          - baz: 'always?'
    steps:
      - run: echo JobB ${{ matrix.foo }} ${{ matrix.bar }} ${{ matrix.baz }}


  job-a:
    name: Job A
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4, 5]
    steps:
      - run: echo JobA ${{ matrix.foo }}

