name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    strategy:
      matrix:
        profile:
          - name: 'full-build-jdk8'
            jdk: 8
          - name: 'full-build-jdk11'
            jdk: 11
          - name: 'full-build-java-tests'
            jdk: 11
          - name: 'full-build-cppunit-tests'
            jdk: 11
        extra: [1,2]
        exclude:
          - profile:
              jdk: 8
    steps:
      - run: echo "Hello world!"
