name: Docker Hub Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo foo
      - uses: docker://alpine:3.8
      - uses: docker://node:lts-slim
      - name: Uses alpine, again!
        uses: docker://alipine:3.8
