name: Includes and Excludes
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        if: false
        continue-on-error: true
      - run: exit 2
        continue-on-error: true
      - run: echo Bar.
