name: Includes and Excludes
on: [push]

jobs:
  job-1:
    if: github.repository == 'Robert-Furth/actions-test'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3]
        bar: [3, 4]
        include:
          - foo: 3
            bar: 5
        exclude:
          - foo: 3
    steps:
      - run: echo FOO ${{ matrix.foo }} BAR ${{ matrix.bar }} BAZ ${{ matrix.baz }}
      
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo BAR
