name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile:
          - name: 'full-build-jdk8'
            jdk: 8
            args: '-Pfull-build apache-rat:check verify -DskipTests spotbugs:check checkstyle:check'
          - name: 'full-build-jdk11'
            jdk: 11
            args: '-Pfull-build apache-rat:check verify -DskipTests spotbugs:check checkstyle:check'
          - name: 'full-build-java-tests'
            jdk: 11
            args: '-Pfull-build verify -Dsurefire-forkcount=1 -DskipCppUnit -Dsurefire.rerunFailingTestsCount=5'
          - name: 'full-build-cppunit-tests'
            jdk: 11
            args: '-Pfull-build verify -Dtest=_ -DfailIfNoTests=false'
        extra: [1,2]
    steps:
      - run: echo "Hello world!"
