name: Matrix Grouping
on: [push]

jobs:
  job-b:
    name: Same Name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4, 5]
    steps:
      - run: echo JobB ${{ matrix.foo }}


  job-a:
    name: Same Name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4, 5]
    steps:
      - run: echo JobA ${{ matrix.foo }}

