name: Includes and Excludes
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4]
        include:
          - foo: 2
            bar: true
          - foo: 4
            baz: 4
          - foo: 5
          - baz: 5
    steps:
      - run: echo ${{ matrix.foo }} ${{ matrix.bar }} ${{ matrix.baz }}
      
  job-2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: [1, 2, 3, 4]
        include:
          - baz: 5
          - foo: 2
            bar: true
          - foo: 4
            baz: 4
          - foo: 5
    steps:
      - run: echo ${{ matrix.foo }} ${{ matrix.bar }} ${{ matrix.baz }}

