name: On Commit
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ['Foo value!']
    steps:
      - run: 'echo Lowercase: ${{ matrix.foo }} ${{ strategy.job-total }}'
      - run: 'echo Mixed case: ${{ matrix.FoO }} ${{ strategy.Job-Total }}'
