name: On Commit
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo: ['Foo value!']
    steps:
      - run: 'echo Lowercaase: ${{ matrix.foo }}'
      - run: 'echo Mixed case: ${{ matrix.FoO }}'
