name: On Commit
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
      
    steps:
      - env:
          ARRAY: [1,2,3]
          OBJECT:
            a: 1
            b: 2
        run: echo "$ARRAY"; echo "$OBJECT"
