name: On Commit
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        A: ["A1", "A2"]
        B: ["B1", "B2"]
        include:
          - A: A3
            B: B3
            C: C3
          - A: A1
            B: B2
            C: C4
      
    steps:
      - run: echo foo
