name: On Commit
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        foo:
          - ${{ github.server_url }}
      
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.foo }}
      - run: ./test.sh
