name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    name: "Test operators"
    steps:
      # ! (1 > -1) --> !true --> false
      # (!1) > -1 --> 0 > -1 --> true
      - run: echo ${{ ! 1 > -1 }}
