name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      FOO: bar
    steps:
      - uses: actions/checkout@v3
      - run: 'pwd; ls -R .*'
      - uses: ./.github/actions/with-pre
      - uses: ./.github/actions/with-pre
