name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      FOO: bar
    steps:
      - run: echo FOO=BAZ >> $GITHUB_ENV
      - run: echo ${{ env.FOO }}
      - run: echo $FOO
