name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ASDFASDFASDFASDFASDF > "${{ runner.name }}"
      - run: echo ${{ hashFiles('./${{ runner.name }}') }}
