name: Test Action
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      FOO: bar.txt
    steps:
      - run: echo ASDFASDFASDFASDFASDF > "${{ env.FOO }}"
      - run: echo ${{ hashFiles('${{ env.FOO }}') }}
